
package com.desknetinc.reportingapptools.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PDFCompareImplService", targetNamespace = "http://webservices.reportingapptools.desknetinc.com/", wsdlLocation = "http://ushoucwpdfc01vd:8080/ReportingAppTools/PDFCompare?wsdl")
public class PDFCompareImplService
    extends Service
{

    private final static URL PDFCOMPAREIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.desknetinc.reportingapptools.webservices.PDFCompareImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.desknetinc.reportingapptools.webservices.PDFCompareImplService.class.getResource(".");
            url = new URL(baseUrl, "http://ushoucwpdfc01vd:8080/ReportingAppTools/PDFCompare?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ushoucwpdfc01vd:8080/ReportingAppTools/PDFCompare?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PDFCOMPAREIMPLSERVICE_WSDL_LOCATION = url;
    }

    public PDFCompareImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PDFCompareImplService() {
        super(PDFCOMPAREIMPLSERVICE_WSDL_LOCATION, new QName("http://webservices.reportingapptools.desknetinc.com/", "PDFCompareImplService"));
    }

    /**
     * 
     * @return
     *     returns PDFCompareService
     */
    @WebEndpoint(name = "PDFCompareImplPort")
    public PDFCompareService getPDFCompareImplPort() {
        return super.getPort(new QName("http://webservices.reportingapptools.desknetinc.com/", "PDFCompareImplPort"), PDFCompareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PDFCompareService
     */
    @WebEndpoint(name = "PDFCompareImplPort")
    public PDFCompareService getPDFCompareImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.reportingapptools.desknetinc.com/", "PDFCompareImplPort"), PDFCompareService.class, features);
    }

}
